user_name = input("Enter your username: ")
# variable name has to be one unit, can be seperated by _
# can't use numbers at the beginning of a variable name
# don't use privilleaged words like input, print etc...
# use sensible names for future understanding eg: color,username,password etc...

